
prompt-sala-bodega.txt																										ren    prompt-sala-bodega.txt																							   
prompt-estado-sala-bodega-muestra-barrica.txt                             ren    prompt-estado-sala-bodega-muestra-barrica.txt                         
prompt-estado-sala-bodega-muestra-prensa.txt                              ren    prompt-estado-sala-bodega-muestra-prensa.txt                          
prompt-sala_del_topo.txt                                                  ren    prompt-sala_del_topo.txt                                              
prompt-estado-sala_del_topo-muestra-mesa.txt                              ren    prompt-estado-sala_del_topo-muestra-mesa.txt                          
prompt-estado-sala_del_topo-muestra-prensa.txt                            ren    prompt-estado-sala_del_topo-muestra-prensa.txt                        
prompt-sala-Carmen_Escalona.txt                                           ren    prompt-sala-Carmen_Escalona.txt                                       
prompt-estado-sala-Carmen_Escalona-muestra-esparto.txt                    ren    prompt-estado-sala-Carmen_Escalona-muestra-esparto.txt                
prompt-estado-sala-Carmen_Escalona-muestra-recogida-aceituna.txt          ren    prompt-estado-sala-Carmen_Escalona-muestra-recogida-aceituna.txt      
prompt-sala-el_campo.txt                                                  ren    prompt-sala-el_campo.txt                                              
prompt-estado-sala-el_campo-muestra-trillo.txt                            ren    prompt-estado-sala-el_campo-muestra-trillo.txt                        
prompt-estado-sala-el_campo-muestra-ubio.txt                              ren    prompt-estado-sala-el_campo-muestra-ubio.txt                          
prompt-sala-exposiciones.txt                                              ren    prompt-sala-exposiciones.txt                                          
prompt-estado-sala-exposiciones-muestra-artesania.txt                     ren    prompt-estado-sala-exposiciones-muestra-artesania.txt                 
prompt-estado-sala-exposiciones-muestra-pintura.txt                       ren    prompt-estado-sala-exposiciones-muestra-pintura.txt                   
prompt-sala-Molinos_de_aceite.txt                                         ren    prompt-sala-Molinos_de_aceite.txt                                     
prompt-estado-sala-Molinos_de_aceite-muestra-molino-sangre.txt            ren    prompt-estado-sala-Molinos_de_aceite-muestra-molino-sangre.txt        
prompt-estado-sala-Molinos_de_aceite-muestra-molino-mecanico.txt          ren    prompt-estado-sala-Molinos_de_aceite-muestra-molino-mecanico.txt      
prompt-sala-panaderia.txt                                                 ren    prompt-sala-panaderia.txt                                             
prompt-estado-sala-panaderia-muestra-horno-de-lenia.txt                   ren    prompt-estado-sala-panaderia-muestra-horno-de-lenia.txt               
prompt-estado-sala-panaderia-muestra-pan-de-mijas.txt                     ren    prompt-estado-sala-panaderia-muestra-pan-de-mijas.txt                 
prompt-sala-sierra.txt                                                    ren    prompt-sala-sierra.txt                                                
prompt-estado-sala-sierra-muestra-encalar.txt                             ren    prompt-estado-sala-sierra-muestra-encalar.txt                         
prompt-estado-sala-sierra-muestra-esparto.txt                             ren    prompt-estado-sala-sierra-muestra-esparto.txt                         
prompt-sala-vivienda_tradicional.txt                                      ren    prompt-sala-vivienda_tradicional.txt                                  
prompt-estado-sala-vivienda-tradicional-muestra-cocina.txt                ren    prompt-estado-sala-vivienda-tradicional-muestra-cocina.txt            
prompt-estado-sala-vivienda-tradicional-muestra-dormitorio.txt            ren    prompt-estado-sala-vivienda-tradicional-muestra-dormitorio.txt        
prompt-estado-S4P1LibroVisitas.txt                                        ren    prompt-estado-S4P1LibroVisitas.txt                                    
prompt-estado-S4P2FirmarLibro.txt                                         ren    prompt-estado-S4P2FirmarLibro.txt                                     
prompt-estado-S4P3Exito.txt                                               ren    prompt-estado-S4P3Exito.txt                                           
prompt-estado-S4P4Error.txt                                               ren    prompt-estado-S4P4Error.txt                                           
prompt-estado-S5P1RealizarEncuesta.txt                                    ren    prompt-estado-S5P1RealizarEncuesta.txt                                
prompt-estado-S5P3Exito.txt                                               ren    prompt-estado-S5P3Exito.txt                                           
prompt-estado-S5P3Error.txt                                               ren    prompt-estado-S5P3Error.txt                                           
prompt-estado-S78P0Multimedia.txt                                         ren    prompt-estado-S78P0Multimedia.txt                                     
prompt-estado-S7P1PublicacionMultimedia.txt                               ren    prompt-estado-S7P1PublicacionMultimedia.txt                           
prompt-estado-S8P1FotografoVirtual.txt                                    ren    prompt-estado-S8P1FotografoVirtual.txt                                
prompt-estado-S8P2SeleccionarMarco.txt                                    ren    prompt-estado-S8P2SeleccionarMarco.txt                                
prompt-estado-S8P3SacarFoto.txt                                           ren    prompt-estado-S8P3SacarFoto.txt                                       
prompt-estado-S8P4AccionFoto.txt                                          ren    prompt-estado-S8P4AccionFoto.txt                                      
prompt-estado-S8P7MandarEMail.txt                                         ren    prompt-estado-S8P7MandarEMail.txt                                     
